공모전 - 7. 삼성 SDS Britics AI(2019.08)/conv2mbti/conv2mbti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mbti_model.urls')),#mbti_model의 urls.py를 포함시켜줌
]


공모전 - 7. 삼성 SDS Britics AI(2019.08)/conv2mbti/mbti_model/urls.py
from django.urls import path
from . import views

app_name = 'mbti_model'


urlpatterns=[
             path('',views.test,name='test'),
             path('result',views.result,name='result')
             ]

공모전 - 7. 삼성 SDS Britics AI(2019.08)/conv2mbti/mbti_model/models.py
from django.db import models

# Create your models here.

공모전 - 7. 삼성 SDS Britics AI(2019.08)/conv2mbti/mbti_model/views.py
from django.shortcuts import render
from django.utils import timezone
from django.shortcuts import  get_object_or_404
import requests
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import numpy as np
from matplotlib import style
import pandas as pd
import pickle
from sklearn.externals import joblib
import csv
from django.http import HttpResponse

# Create your views here.
def test(request):
    return render(request, 'mbti_model/index.html')

def result(request):
    if request.method == "GET":
        sepal_length = request.GET.get('sepalLength')
        sepal_width = request.GET.get('sepalWidth')
        petal_length =request.GET.get('petalLength')
        petal_width = request.GET.get('petalWidth')
       
        #csv.DictReader
        

        iris_test = pd.DataFrame({'sepal length (cm)':[sepal_length],
             'sepal width (cm)':[sepal_width],
             'petal length (cm)':[petal_length],
             'petal width (cm)':[petal_width]})

        model = joblib.load('/Users/tlsal/samsungsds-project/shinminyong/conv2mbti/mbti_model/is_model.pkl')

        pred = model.predict(iris_test)[0]

        return render(request, 'mbti_model/result.html', {'pred' : pred})



공모전 - 7. 삼성 SDS Britics AI(2019.08)/conv2mbti/mbti_model/templates/mbti_model/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width,
           initial-scale=1,
           user-scalable=no,
           shrink-to-fit=no">
    <title>SAMSUNG SDS</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/input.css">
</head>

<body>
    <form class='input-form' method="get", name="input_form" action="{% url 'mbti_model:result' %}">
        <fieldset>
            <legend>Conversation to MBTI</legend>
            <!-- 성명: <br>
            <input type="text" name="name"> <br>
            성별: <br>
            <input type="radio" name="gender" value="male" checked> 남<br>
            <input type="radio" name="gender" value="female"> 녀<br>
            <input type="radio" name="gender" value="other"> 불명<br>
            대화내용: <br>
            <input type="file" name="talk_log"> <br> -->
            <input type="text" name="sepalLength" placeholder="SepalLength">
            <input type="text" name="sepalWidth" placeholder="SepalWidth">
            <input type="text" name="petalLength" placeholder="PetalLength">
            <input type="text" name="petalWidth" placeholder="PetalWidth">
            <input type="file" name="file">
            <input type="submit" value="가자ㅏ!">
        </fieldset>
    </form>
</body>

<script>
</script>

</html>

공모전 - 7. 삼성 SDS Britics AI(2019.08)/conv2mbti/mbti_model/templates/mbti_model/result.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width,
           initial-scale=1,
           user-scalable=no,
           shrink-to-fit=no">
    <title>SAMSUNG SDS</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/input.css">
</head>

<body>
    당신은 {{pred}}의 성격을 지녔습니다.
</body>

<scirpt>
</scirpt>

</html>

공모전 - 7. 삼성 SDS Britics AI(2019.08)/conv2mbti/mbti_model/templates/mbti_model/test.html
<h1>hello world</h1>